<?php
include('../connect.php');	

$LETTER_REF = $_POST['LETTER REF'];
$ADDRESSED_TO = $_POST['ADDRESSED TO'];
$SUBJECT = $_POST['SUBJECT'];
$DATE_OF_LETTER = $_POST['DATE OF LETTER'];
$DATE_RECEIEVED_AT_REGISTRY = $_POST['DATE RECEIEVED AT REGISTRY'];
$RECIPIENT = $_POST['RECIPIENT'];
$DATE_DELIVERED = $_POST['DATE DELIVERED'];
$FILE_NAME = $_POST['FILE NAME'];
$FILE_NO = $_POST['FILE NO'];
$BOX_NO = $_POST['BOX NO'];

// query
$sql = "INSERT INTO letters_without_reference2021 (LETTER REF,ADDRESSED TO,SUBJECT,DATE OF LETTER,DATE RECEIEVED AT REGISTRY,RECIPIENT,DATE DELIVERED,FILE NAME,FILE NO,BOX NO) VALUES (:ent1,:ent2,:ent3,:ent4,:ent5,:ent6,:ent7,:ent8,:ent9,:ent10)";
$q = $db->prepare($sql);
$q->execute(array(':ent1'=>$LETTER_REF,':ent2'=>$ADDRESSED_TO,':ent3'=>$SUBJECT,':ent4'=>$DATE_OF_LETTER,':ent5'=>$DATE_RECEIEVED_AT_REGISTRY,':ent6'=>$RECIPIENT,':ent7'=>$DATE_DELIVERED,':ent8'=>$FILE_NAME,':ent9'=>$FILE_NO,':ent10'=>$BOX_NO));
header("location: index.php");


?>